In [4]:
import torch as t
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
torch.manual_seed(1)

In [11]:
# creating tensors
V_data = [1.,2.,3.]
V = torch.tensor(V_data)

# create a matrix
M = torch.tensor([[1.,2.,3.],[4.,5.,6.]])

# create a 3D tensor of size 2 x 2 x 2
T_data = [[[1., 2.], [3., 4.]],
          [[5., 6.], [7., 8.]]]
T = torch.tensor(T_data)

In [14]:
# tensor addition
A = torch.tensor([1,2,3])
B = torch.tensor([4,5,6])

C = A+B

In [27]:
# randn
x_1 = torch.randn(2,5)
y_1 = torch.randn(3,5)
z_1 = torch.cat([x_1, y_1], 0)
print(z_1)

tensor([[-0.3749,  1.8673,  0.9042,  0.1181,  1.8941],
        [-0.4229,  0.7431,  0.0756,  1.1366, -1.9280],
        [-0.5565, -0.1434,  2.6780,  0.6735,  0.4161],
        [-1.0110,  0.5515,  0.9910, -1.0281, -0.9821],
        [-1.8680,  0.5865, -0.4641, -0.9715, -1.0603]])


In [28]:
# concatenate coumns:
x_2 = torch.randn(2, 3)
y_2 = torch.randn(2, 5)

# second arg specifies which axis to concat, 1 means concat columns
z_2 = torch.cat([x_2, y_2], 1)
print(z_2)

tensor([[ 0.7090, -0.0895, -0.8338,  0.8562, -1.0990,  0.2927,  0.8433,
          0.0486],
        [ 0.4515, -0.9094,  0.0729,  1.2114, -1.4602,  1.7995,  0.5176,
         -1.1685]])


In [39]:
# reshape
x = torch.randn(2, 3, 4)
print(x)
print(x.view(2,12)) # Reshape to 2 rows, 12 columns
print(x.view(-1)) # flat

tensor([[[-1.1414, -1.9074, -1.1947, -0.0979],
         [ 0.6432,  0.8004,  0.4092,  0.3018],
         [-1.1615,  2.7769,  0.4533,  1.0132]],

        [[ 2.8881,  1.5409, -0.4591, -0.5763],
         [ 0.3502,  0.9340,  0.0843,  0.2034],
         [-0.3605, -1.1880, -1.3643,  0.5805]]])
tensor([[-1.1414, -1.9074, -1.1947, -0.0979,  0.6432,  0.8004,  0.4092,
          0.3018, -1.1615,  2.7769,  0.4533,  1.0132],
        [ 2.8881,  1.5409, -0.4591, -0.5763,  0.3502,  0.9340,  0.0843,
          0.2034, -0.3605, -1.1880, -1.3643,  0.5805]])
tensor([-1.1414, -1.9074, -1.1947, -0.0979,  0.6432,  0.8004,  0.4092,
         0.3018, -1.1615,  2.7769,  0.4533,  1.0132,  2.8881,  1.5409,
        -0.4591, -0.5763,  0.3502,  0.9340,  0.0843,  0.2034, -0.3605,
        -1.1880, -1.3643,  0.5805])


In [44]:
# knows its creation
x = torch.tensor([1,2], requires_grad = True)
y = torch.tensor([3,4], requires_grad = True)

z = x + y
print(z)
print(z.grad_fn)

tensor([ 4,  6])


In [47]:
# compute gradient
s = z.sum()
print(s)
print(s.grad_fn)

tensor(10)


In [50]:
# run backprop
s.backward()
print(x.grad)

tensor([ 3,  3])
